replicaCount: 2
image:
  repository: vinhbh/vdt_web
  pullPolicy: IfNotPresent
  tag: "v3.1"

securityContext: {}

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30001
  portName: vdt-web-port

resources: {}

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
